StringTable {
 ItemClassName "CustomStringTableItem"
 Items {
  CustomStringTableItem "{62045977BA65F50D}" {
   Id "AR-V30_MapVoting_FactionName"
   Target_en_us "Electorate"
   Target_ru_ru "Избиратели"
   Modified 1644452258
   Author "Vlad333000"
   LastChanged "Vlad333000"
  }
  CustomStringTableItem "{62045977EF2D462B}" {
   Id "AR-V30_MapVoting_FactionName_UC"
   Target_en_us "ELECTORATE"
   Target_ru_ru "ИЗБИРАТЕЛИ"
   Modified 1644452394
   Author "Vlad333000"
   LastChanged "Vlad333000"
  }
  CustomStringTableItem "{62043BCE8625247F}" {
   Id "AR-V30_MapVoting_MenuChoiceSubTitle"
   Target_en_us "Subtitle"
   Target_ru_ru "Подзаголовок"
   Modified 1644446224
   Author "Vlad333000"
   LastChanged "Vlad333000"
  }
  CustomStringTableItem "{62043BCE9F2D5D09}" {
   Id "AR-V30_MapVoting_MenuChoiceTitle"
   Target_en_us "Title"
   Target_ru_ru "Заголовок"
   Modified 1644446222
   Author "Vlad333000"
   LastChanged "Vlad333000"
  }
  CustomStringTableItem "{62043BCE8EBD8AF4}" {
   Id "AR-V30_MapVoting_MenuEndTitle"
   Target_en_us "Next scenario:"
   Target_ru_ru "Следующий сценарий:"
   Modified 1644446220
   Author "Vlad333000"
   LastChanged "Vlad333000"
  }
  CustomStringTableItem "{62043BCEFA298107}" {
   Id "AR-V30_MapVoting_MenuScreenTitle"
   Target_en_us "VOTE!"
   Target_ru_ru "ГОЛОСОВАНИЕ!"
   Modified 1644446218
   Author "Vlad333000"
   LastChanged "Vlad333000"
  }
  CustomStringTableItem "{6688B26F3FC0AA12}" {
   Id "AR-V30_MapVoting_MenuWaitingTitle"
   Target_en_us "Waiting for the voting to begin"
   Target_ru_ru "Ожидание начала голосования"
   Modified 1720235383
   Author "Vlad333000"
   LastChanged "Vlad333000"
  }
  CustomStringTableItem "{62043BCEEB54E727}" {
   Id "AR-V30_MapVoting_MissionAuthor"
   Target_en_us "Vlad333000"
   Modified 1644446215
   Author "Vlad333000"
   LastChanged "Vlad333000"
  }
  CustomStringTableItem "{62043BCEC0C0C534}" {
   Id "AR-V30_MapVoting_MissionDescription"
   Target_en_us "Long live democracy! Everybody to the polls!"
   Target_ru_ru "Да здравствует демократия! Все на выборы!"
   Modified 1644446211
   Author "Vlad333000"
   LastChanged "Vlad333000"
  }
  CustomStringTableItem "{62048E786383621F}" {
   Id "AR-V30_MapVoting_MissionDetails"
   Target_en_us "1. Select your scenario you want to play;"\
   "2. Promoto it to other players;"\
   "3. And hope that your scenario will be next."
   Target_ru_ru "1. Выбери сценарий, который ты хочешь играть;"\
   "2. Продвигай его среди других игроков;"\
   "3. И надейся, что именно твой сценарий будет следующий."
   Modified 1644467034
   Author "Vlad333000"
   LastChanged "Vlad333000"
  }
  CustomStringTableItem "{62043BCEE91B4BE5}" {
   Id "AR-V30_MapVoting_MissionTitle"
   Target_en_us "Map Voting"
   Target_ru_ru "Голосование"
   Modified 1644446209
   Author "Vlad333000"
   LastChanged "Vlad333000"
  }
  CustomStringTableItem "{62043BCE32E0E0AC}" {
   Id "AR-V30_MapVoting_RandomChoiceSubTitle"
   Target_en_us "Unknown"
   Target_ru_ru "Неизвестно"
   Modified 1644446202
   Author "Vlad333000"
   LastChanged "Vlad333000"
  }
  CustomStringTableItem "{62043BCE30D7B22D}" {
   Id "AR-V30_MapVoting_RandomChoiceTitle"
   Target_en_us "Random"
   Target_ru_ru "Случаный"
   Modified 1644446200
   Author "Vlad333000"
   LastChanged "Vlad333000"
  }
  CustomStringTableItem "{668AD0F9F308692A}" {
   Id "AR-V30_MapVoting_SimplePreGame_WaitingDelay"
   Target_en_us "Starting vote in %1"
   Target_ru_ru "Начало голосования через %1"
   Modified 1720375149
   Author "Vlad333000"
   LastChanged "Vlad333000"
  }
  CustomStringTableItem "{62045977E7D98675}" {
   Id "AR-V30_MapVoting_SimplePreGame_WaitingPlayers"
   Target_en_us "Waiting for %1 more player(s)"
   Target_ru_ru "Ожидание еще %1 игрока(-ов)"
   Modified 1720372719
   Author "Vlad333000"
   LastChanged "Vlad333000"
  }
  CustomStringTableItem "{646307F3CA58268E}" {
   Id "AR-V30_MapVoting_UnknownChoiceSubTitle"
   Target_en_us "Unknown"
   Target_ru_ru "Неизвестно"
   Modified 1684214943
   Author "Vlad333000"
   LastChanged "Vlad333000"
  }
  CustomStringTableItem "{646307F3D6540BCE}" {
   Id "AR-V30_MapVoting_UnknownChoiceTitle"
   Target_en_us "Unknown scenario"
   Target_ru_ru "Неизвестный сценарий"
   Modified 1684215261
   Author "Vlad333000"
   LastChanged "Vlad333000"
  }
 }
}