SystemSettings : "{86E953538A28A98D}Configs/Systems/ChimeraSystemsConfig.conf" {
 Systems {
  V30_MapVoting_WorldTimestampSyncWorldSystem "{68A6FA45970A3261}" {
  }
  V30_MapVoting_VotingWorldSystem "{68B0CA89DFC57427}" {
   SystemLocation Server
   SystemPoints 0 0x10
  }
 }
}