ActionManager {
 Actions {
  Action V30_MapVoting_RemoveVote {
   InputSource InputSourceSum "{6848ED8D9AE2704C}" {
    Sources {
     InputSourceValue "{6848ED8DFBE2D66A}" {
      Input "keyboard:KC_R"
      Filter InputFilterClick "{6848ED8DC4280AEE}" {
      }
     }
     InputSourceValue "{6848ED8D38B89AAC}" {
      Input "gamepad0:x"
      Filter InputFilterClick "{6848ED8D23F4A439}" {
      }
     }
    }
   }
  }
  Action V30_MapVoting_EndVote {
   InputSource InputSourceSum "{6848ED8D10CF2605}" {
    Sources {
     InputSourceValue "{6848ED8D16515809}" {
      Input "keyboard:KC_Y"
      Filter InputFilterHoldOnce "{6848ED8D04203049}" {
      }
     }
     InputSourceValue "{6848ED8D0BA130C3}" {
      Input "gamepad0:y"
      Filter InputFilterHoldOnce "{6848ED8D71BBF5C9}" {
      }
     }
    }
   }
  }
 }
 Contexts {
  ActionContext V30_MapVoting_MenuContext {
   Priority 50
   Flags 0x4 0
   ActionRefs {
    "MenuLeft"
    "MenuRight"
    "MenuUp"
    "MenuDown"
    "MenuSelect"
    "MenuOpen"
    "MenuNavRight"
    "MenuNavLeft"
    "MenuNavRight_NoScroll"
    "MenuNavLeft_NoScroll"
    "VONDirect"
    "VONChannel"
    "ChatToggle"
    "InstantVote"
    "EditorToggle"
    "MenuRefresh"
   }
  }
  ActionContext V30_MapVoting_GameOverScreenVotingMenuContext {
   Priority 50
   Flags 0x4 0
   ActionRefs {
    "MenuBack"
    "MenuSelect"
    "MenuLeft"
    "MenuRight"
    "MenuUp"
    "MenuDown"
    "MenuNavRight"
    "MenuNavLeft"
    "ChatToggle"
    "V30_MapVoting_RemoveVote"
    "V30_MapVoting_EndVote"
   }
  }
 }
}